#%RAML 1.0 DataType
type: object

description: Representation of Bad Request - See https://tools.ietf.org/html/rfc7235#section-3.1
displayName: 401 - Unauthorized

properties: 
      message: 
        type: string
        displayName: Message
        description: The HTTP status code message
example: !include ../examples/401-unauthorized.json