#%RAML 1.0 DataType
description: Representation Not found - See https://tools.ietf.org/html/rfc7231#section-6.5.4
displayName: 404 - Not Found

properties: 
      message: 
        type: string
        displayName: Message
        description: The HTTP status code message
      
example: !include ../examples/404-not-found.json