#%RAML 1.0 DataType
description: Defines the response fields of warehouse database

type: object  
properties:
  wh:
    type: integer
    description: 'wh'
  wh_name:
    type: string
    description: 'wh_name'
  facility:
    type: number
    description: 'facility'
  warehouse_code:
    type: integer
    description: 'warehouse_code'
  wh_live_ind:
    type: string
    description: 'wh_live_ind'